version: '3.3'

services:
  # FastAPI Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: minio-api:latest
    container_name: minio-api
    ports:
      - "8113:8113"
    environment:
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - .:/app
    restart: unless-stopped